version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://username:password@db/db_name
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
